### ISSUE TITLE
Make `Task`s more configurable

### ISSUE THREAD

**Issue by haileyschoelkopf** [EleutherAI/lm-eval2#10]
The lm-evaluation-harness currently operates around Task classes that contain the necessary information to load a task's data from a Huggingface dataset, and contain the logic used to actually score and return the proper metric for a task. 

Tasks currently hardcode a number of things, including 
- The input format to feed to a model (the "prompt")
- What type of completion (in the old implementation: "request_type") to request from a model: some things like Chain-of-thought prompting may require converting a task to a generation task from a multiple choice task, then providing a post-processing step to grab labels from these generations.
- 

We would like to give users control over these things, though sensible defaults should be included within tasks so that a non-advanced user can just specify, e.g. , `--tasks arc_easy` and run from the CLI without providing more configuration details for a task.

The most relevant configuration to implement here would be allowing users to provide **prompt templates** using either F-strings or prompts from Promptsource (https://github.com/bigscience-workshop/promptsource ) to create prompts.

**Comment by lintangsutawika** [comment]
I can investigate this task

**Comment by haileyschoelkopf** [comment]
Awesome! I added a preliminary config field to the Tasks here. 

I think Bigscience's fork may have included a way to pass configs to tasks?

Probably the most important thing to make configurable is letting a user set their own prompt to use--do you have ideas on how to set that up or what else to make configurable?

**Comment by lintangsutawika** [comment]
Users are already able to prompt through `doc_to_text` though, right?

For chain of thought should we add it to `Task` or make it as a separate object?

**Comment by lintangsutawika** [comment]
Looks like with a `self._config` we can make it so that each function like `has_training_docs` etc can be configured from there as a default. They can still be overwritten for more advance users.

**Comment by lintangsutawika** [comment]
Or pass a function in YAML? I think that could work too. Maybe some prompts can be written in simple python function and be passed to lm-eval through YAML.

**Comment by haileyschoelkopf** [comment]
I like this a bunch, this is what I maybe had in mind! I think we should try YAMLs.

> Or pass a function in YAML? I think that could work too. Maybe some prompts can be written in simple python function and be passed to lm-eval through YAML.

Hmm, the one thing I'm worried I didn't think through enough is that, would some of these configuration details be more confusing to pass via config files than just having someone edit the Task class in the code? I guess I _think_ that not needing code edits and allowing someone to "share" a task/eval setup just by sharing their YAML and maybe their user defined postprocessing seems more convenient, but not sure...

**Comment by lintangsutawika** [comment]
Current draft PR  #11 to illustrate how it would work.

```
import yaml
from lm_eval.api.task import ConfigurableTask

with open("sglue_cb.yaml", 'r') as f:
    config = yaml.load(f, yaml.Loader)

task = ConfigurableTask(config=config)
```

So I'm thinking we make a `ConfigurableTask` which is a boilerplate task object. It's configurable through a yaml but would probably lack customization for methods like `construct_requests` and `process_results`

**Comment by lintangsutawika** [comment]
I've made it so that it can process jinja templates. But I couldn't get it to run yet because I'm not sure how to use `GenerationInstance`.

**Comment by haileyschoelkopf** [comment]
Responded via DM so we can discuss this further!
